apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: spider-test-scaledobject
spec:
  scaleTargetRef:
    name: spider-test  # Deployment name
  pollingInterval: 30  # Interval to check the metric
  cooldownPeriod:  300  # Period to wait before scaling down
  minReplicaCount: 0
  maxReplicaCount: 20  # Maximum number of replicas
  triggers:
  - type: rabbitmq  # Replace with your event source
    metadata:
      host: amqp://production-rabbitmqcluster.default.svc.cluster.local  # Environment variable with the connection string
      username: guest  # RabbitMQ username
      password: guest  # RabbitMQ password
      port: "5672"  # RabbitMQ port
      queueName: scrapy_queue  # Replace with your queue name
      queueLength: "5"  # Scale for each message
