apiVersion: apps/v1
kind: Deployment
metadata:
  name: spider-test
spec:
  replicas: 0  # Start with zero replicas
  selector:
    matchLabels:
      app: spider-test
  template:
    metadata:
      labels:
        app: spider-test
    spec:
      containers:
      - name: spi-con
        image: mqcons:1.2  # Replace with your container image
        envFrom:
        - configMapRef:
            name: spider-env-config
        - secretRef:
            name: spider-env-secret
        imagePullPolicy: Never
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
